### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void slib.platform.android.Android.nativeOnCreateActivity(android.app.Activity)

### ISSUE THREAD

**Issue by bilsou** [SLIBIO/SLib#21]
Me again. 
As I am waiting for the iOS example, I've been trying to at least test the Android part as I saw there was a JNI example in the `examples` folder. 
So the basic example does run. But as soon as I try to use the `SLibActivity` on the Java side I end up with the error specified in the title
Here is the full bug report:

**What steps will reproduce the problem?**

1. Build and run the JNI example
2. JNI example runs without any error
3. In MainActivity,  add 

```java
Intent intent = new Intent(this, VideoActivity.class);
this.startActivity(intent);
```
to `onCreate`

with VideoActivity as follows:

```java
public class VideoActivity extends SlibActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        Log.d("VideoActivity", "onCreate");

    }
}
```
4. The app crashes

**What is the expected result?**

The app should not crash

**What do you see instead?**

1. The app crashes with:
```
Java_slib_platform_android_Android_nativeOnCreateActivity and Java_slib_platform_android_Android_nativeOnCreateActivity__Landroid_app_Activity_2)
                                                       at slib.platform.android.Android.nativeOnCreateActivity(Native Method)
                                                       at slib.platform.android.Android.onCreateActivity(Android.java:42)
                                                       at slib.platform.android.SlibActivity.onCreate(SlibActivity.java:39)
                                                       at android.app.Activity.performCreate(Activity.java:6813)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:203)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6251)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**What version of the product are you using? On what operating system?**

Version v0.1.4 - Android 7.0

**Please provide any additional information below.**

1. I am not sure what is going on, why the linking error happens as the`native-lib.so` gets loaded properly but then at runtime, calling `Android.nativeOnCreateActivity` crashes

Hope you will be able to help out, I'm just trying to get a camera feed.

**Comment by fred1218zh** [comment]
Please make sure that you added following code in `main.cpp` for .so file

```
#include <slib/core/platform_android.h>

JNIEXPORT jint JNI_OnLoad(JavaVM* jvm, void* reserved)
{
	slib::Android::initialize(jvm);
	return JNI_VERSION_1_4;
}
```

**Comment by bilsou** [comment]
I do have that. Sorry for not specifying it.
Here is what I have in `native-lib.cpp`

```cpp
#include <jni.h>

#include <slib/core.h>
#include <slib/core/platform_android.h>
#include <slib/ui/platform.h>
#include "slib/ui/screen.h"
#include "slib/ui/platform.h"
#include "slib/ui/mobile_app.h"
#include "slib/core/io.h"
#include "slib/core/log.h"
#include "slib/core/safe_static.h"

using namespace slib;

JNIEXPORT jint JNI_OnLoad(JavaVM* jvm, void* reserved)
{
	Android::initialize(jvm);
	return JNI_VERSION_1_4;
}
```

I even added other headers as you can see. But with or without them, still crashes on `Android.nativeOnCreateActivity`

**Comment by fred1218zh** [comment]
You don't need to include other headers.
Please check you loaded native library.
```
public class VideoActivity extends SlibActivity {

   static {
      System.loadLibrary("native-lib");
   }

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        Log.d("VideoActivity", "onCreate");

    }
}
```

**Comment by fred1218zh** [comment]
Additionally,
You should check your device abi - x86, arm7, arm64, and you are building .so file regarding that abi.

**Comment by bilsou** [comment]
I already had 
```java
    static {
        System.loadLibrary("native-lib");
    }
```
in VideoActivity.
I also removed the unnecessary headers but still no success.
As for the .so library when I build the JNI example, all the different abi flavours get resp. generated in 
`SLib/examples/JNI(Android)/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so` 
`SLib/examples/JNI(Android)/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so` 
`SLib/examples/JNI(Android)/app/build/intermediates/cmake/debug/obj/x86/libnative-lib.so`

**Comment by bilsou** [comment]
I just followed the build instructions for Android but maybe the way the static libraries are linked to the `libnative-lib.so` shared library is wrong somehow

**Comment by fred1218zh** [comment]
Ah,
To use UI related features, you have to define Application in native side.
Please add following snippet in `main.cpp`

```
#include <slib/ui.h>
#include <slib/core/platform_android.h>

using namespace slib;

class TestApp : public MobileApp {
public:
 SLIB_DECLARE_APPLICATION(TestApp);
 void onStart() {
 }
 void onCreateActivity() {
 }
 void onDestroyActivity() {
 }
 void onResume() {
 }
 void onPause() {
 }
};

SLIB_DEFINE_APPLICATION(TestApp, MobileApp);

JNIEXPORT jint JNI_OnLoad(JavaVM* jvm, void* reserved)
{
	Android::initialize(jvm);
        TestApp::main();
	return JNI_VERSION_1_4;
}
```

**Comment by bilsou** [comment]
Just put that in my `native-lib.cpp` and got errors related to `opengl_impl.h`

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/bils/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/bils/Github/SLib/examples/JNI(Android)/app/.externalNativeBuild/cmake/debug/x86 --target native-lib}
  [1/2] /Users/bils/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=i686-none-linux-android --gcc-toolchain=/Users/bils/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/bils/Library/Android/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -I/Users/bils/Github/SLib/include -isystem /Users/bils/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/bils/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -isystem /Users/bils/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /Users/bils/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c "/Users/bils/Github/SLib/examples/JNI(Android)/app/src/main/cpp/native-lib.cpp"
  [2/2] : && /Users/bils/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=i686-none-linux-android --gcc-toolchain=/Users/bils/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/bils/Library/Android/sdk/ndk-bundle/sysroot -fPIC -isystem /Users/bils/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /Users/bils/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-x86 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -L/Users/bils/Github/SLib/lib/Android/Debug-x86 -lslib -llog -latomic -lm "/Users/bils/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_static.a" && :
  FAILED: : && /Users/bils/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=i686-none-linux-android --gcc-toolchain=/Users/bils/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/bils/Library/Android/sdk/ndk-bundle/sysroot -fPIC -isystem /Users/bils/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /Users/bils/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-x86 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -L/Users/bils/Github/SLib/lib/Android/Debug-x86 -lslib -llog -latomic -lm "/Users/bils/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_static.a" && :
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:38: error: undefined reference to 'glViewport'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:45: error: undefined reference to 'glClearColor'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:52: error: undefined reference to 'glClearDepthf'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:57: error: undefined reference to 'glClearStencil'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:61: error: undefined reference to 'glClear'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:96: error: undefined reference to 'glEnable'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:98: error: undefined reference to 'glDisable'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:104: error: undefined reference to 'glDepthMask'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:132: error: undefined reference to 'glDepthFunc'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:138: error: undefined reference to 'glEnable'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:139: error: undefined reference to 'glCullFace'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:141: error: undefined reference to 'glFrontFace'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:143: error: undefined reference to 'glFrontFace'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:146: error: undefined reference to 'glDisable'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:203: error: undefined reference to 'glEnable'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:207: error: undefined reference to 'glBlendEquationSeparate'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:209: error: undefined reference to 'glBlendEquation'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:216: error: undefined reference to 'glBlendFunc'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:218: error: undefined reference to 'glBlendFuncSeparate'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:220: error: undefined reference to 'glBlendColor'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:222: error: undefined reference to 'glDisable'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:234: error: undefined reference to 'glCreateShader'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:239: error: undefined reference to 'glShaderSource'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:240: error: undefined reference to 'glCompileShader'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:242: error: undefined reference to 'glGetShaderiv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:248: error: undefined reference to 'glGetShaderInfoLog'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:257: error: undefined reference to 'glDeleteShader'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:275: error: undefined reference to 'glDeleteShader'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:281: error: undefined reference to 'glCreateProgram'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:288: error: undefined reference to 'glAttachShader'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:295: error: undefined reference to 'glLinkProgram'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:297: error: undefined reference to 'glGetProgramiv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:303: error: undefined reference to 'glGetProgramInfoLog'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:312: error: undefined reference to 'glCreateProgram'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:334: error: undefined reference to 'glDeleteProgram'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:327: error: undefined reference to 'glUseProgram'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:341: error: undefined reference to 'glGenBuffers'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:343: error: undefined reference to 'glBindBuffer'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:344: error: undefined reference to 'glBufferData'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:353: error: undefined reference to 'glBindBuffer'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:354: error: undefined reference to 'glBufferSubData'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:375: error: undefined reference to 'glBindBuffer'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:380: error: undefined reference to 'glBindBuffer'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:412: error: undefined reference to 'glDeleteBuffers'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:419: error: undefined reference to 'glGetAttribLocation'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:428: error: undefined reference to 'glEnableVertexAttribArray'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:429: error: undefined reference to 'glVertexAttribPointer'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:452: error: undefined reference to 'glDisableVertexAttribArray'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:459: error: undefined reference to 'glGetUniformLocation'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:468: error: undefined reference to 'glUniform1f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:475: error: undefined reference to 'glUniform1fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:482: error: undefined reference to 'glUniform1i'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:489: error: undefined reference to 'glUniform1iv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:496: error: undefined reference to 'glUniform2f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:503: error: undefined reference to 'glUniform2f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:510: error: undefined reference to 'glUniform2fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:517: error: undefined reference to 'glUniform2i'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:524: error: undefined reference to 'glUniform2iv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:531: error: undefined reference to 'glUniform3f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:538: error: undefined reference to 'glUniform3f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:545: error: undefined reference to 'glUniform3fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:552: error: undefined reference to 'glUniform3i'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:559: error: undefined reference to 'glUniform3iv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:566: error: undefined reference to 'glUniform4f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:573: error: undefined reference to 'glUniform4f'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:580: error: undefined reference to 'glUniform4fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:587: error: undefined reference to 'glUniform4i'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:594: error: undefined reference to 'glUniform4iv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:606: error: undefined reference to 'glUniformMatrix2fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:622: error: undefined reference to 'glUniformMatrix2fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:639: error: undefined reference to 'glUniformMatrix3fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:660: error: undefined reference to 'glUniformMatrix3fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:684: error: undefined reference to 'glUniformMatrix4fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:712: error: undefined reference to 'glUniformMatrix4fv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:719: error: undefined reference to 'glUniform1i'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:730: error: undefined reference to 'glUniform1iv'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:757: error: undefined reference to 'glDrawArrays'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:762: error: undefined reference to 'glDrawElements'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:767: error: undefined reference to 'glLineWidth'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:772: error: undefined reference to 'glFlush'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:778: error: undefined reference to 'glGenTextures'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:782: error: undefined reference to 'glBindTexture'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:784: error: undefined reference to 'glTexImage2D'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:795: error: undefined reference to 'glTexImage2D'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:809: error: undefined reference to 'glGenTextures'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:811: error: undefined reference to 'glBindTexture'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:812: error: undefined reference to 'glTexImage2D'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:906: error: undefined reference to 'glTexSubImage2D'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:917: error: undefined reference to 'glTexSubImage2D'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:971: error: undefined reference to 'glActiveTexture'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:976: error: undefined reference to 'glBindTexture'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:981: error: undefined reference to 'glBindTexture'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:1010: error: undefined reference to 'glTexParameteri'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:1014: error: undefined reference to 'glTexParameteri'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:1041: error: undefined reference to 'glTexParameteri'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:1045: error: undefined reference to 'glTexParameteri'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:1058: error: undefined reference to 'glDeleteTextures'
  /Users/bils/Github/SLib/src/slib/render/opengl_impl.h:1562: error: undefined reference to 'glGetIntegerv'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.124 secs


```

**Comment by fred1218zh** [comment]
it will be fixed by adding `gl` dependency in `CMakeLists.txt`

```
target_link_libraries(
 native_lib
 slib
 GLESv2
 ${log-lib}
)
```

**Comment by bilsou** [comment]
I had to remove the x86 filter in `        ndk {   abiFilters 'armeabi-v7a', 'arm64-v8a' }` but now it runs without crashing, thanks a lot for your help. It could not find the `slib` static lib for x86 for whatever reason.
Now I need to start that camera and render it so I can see something.

**Comment by bilsou** [comment]
I saw that `SCamera.onResumeActivity(this);` is called in SlibActivity's `onResume`. So I need to manually call `SCamera.create(id, nativeObject)` before being able to open the camera and render the camera's SurfaceTexture. My only question is what's the `nativeObject` I need to pass to the `create` method?

**Comment by fred1218zh** [comment]
`SCamera.create(id, nativeObject)` is called by native library - `Camera` (slib/media/camera.h) and you can't call `SCamera` directly.
Please use `Camera::create()`

**Comment by bilsou** [comment]
Shame on me, it's meant to be called from the C++ side indeed.
Tricky to ask for the runtime permissions before the TestApp's `onStart` gets called. I guess I can't create the camera before checking for the runtime permissions on the Java side

**Comment by fred1218zh** [comment]
You can ask the permissions on the Java side and call a native function (please define an additional export in `main.cpp`) later to create `Camera` instance.
You don't need to create `Camera` instance in `onStart()` callback.

**Comment by bilsou** [comment]
Just did that, managed to create the camera and starting it after making sure the permissions are granted.
Only things is I can't see any camera feed on my `VideoActivity`. Do I need to attach the `SurfaceTexture` somehow to my VideoActivity view ?

Here is what I have right now:

native-lib.cpp
```
#include <jni.h>

#include <slib/core.h>
#include <slib/core/platform_android.h>
#include <slib/ui.h>

using namespace slib;

class CameraApp : public MobileApp {
public:
SLIB_DECLARE_APPLICATION(CameraApp);
	void onStart() override {

	}

	void onCreateActivity() override {

	}

	void onDestroyActivity() override {
	
	}

	void onResume() override {

	}

	void onPause() override {

	}

	auto getCamera() -> Ref<Camera> const {
		return mCamera;
	}

	auto setCamera(Ref<Camera> camera) {
		mCamera = camera;
	}

private:
    Ref<Camera> mCamera;
};

SLIB_DEFINE_APPLICATION(CameraApp, MobileApp);

JNIEXPORT jint JNI_OnLoad(JavaVM* jvm, void* reserved)
{
	Android::initialize(jvm);
	CameraApp::main();
	return JNI_VERSION_1_4;
}

SLIB_JNI_BEGIN_CLASS(MainActivity, "io/slib/examplejni/MainActivity")
    SLIB_JNI_METHOD(startCameraJava, "startCameraJava", "()V")
SLIB_JNI_END_CLASS

extern "C"
JNIEXPORT void JNICALL
Java_io_slib_examplejni_MainActivity_startCameraCpp(JNIEnv *env, jobject thiz) {
	JniGlobal<jobject> activity(thiz);

	const auto camApp = CameraApp::getApp();
	camApp->setCamera(Camera::create(CameraParam()));

	const auto camera = camApp->getCamera();
	camera->start();

	MainActivity::startCameraJava.call(activity.get());

	Log("JNI", "Started camera");
}
```

MainActivity.java

```
public class MainActivity extends AppCompatActivity {

	static {
		System.loadLibrary("native-lib");
	}

	private static final int CAMERA_REQUEST_CODE = 100;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
			if (checkSelfPermission(Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
				requestPermissions(new String[] {
									Manifest.permission.CAMERA
								   }, CAMERA_REQUEST_CODE);
			} else {
				startCameraCpp();
			}
		} else {
			startCameraCpp();
		}
	}

	private void startVideoActivity() {
		Intent intent = new Intent(this, VideoActivity.class);
		intent.setAction(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
		this.startActivity(intent);
	}

	@Override
	public void onRequestPermissionsResult(int requestCode,
										   @NonNull String[] permissions,
										   @NonNull int[] grantResults) {

		super.onRequestPermissionsResult(requestCode, permissions, grantResults);

		if (requestCode == CAMERA_REQUEST_CODE) {

			if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
				Toast.makeText(this, "camera permission granted", Toast.LENGTH_LONG).show();

				startCameraCpp();
			} else {
				Toast.makeText(this, "camera permission denied", Toast.LENGTH_LONG).show();
			}

		}
	}

	/**
	 * A native method that is implemented by the 'native-lib' native library,
	 * which is packaged with this application.
	 */
	public native void startCameraCpp();

	public void startCameraJava() {
		runOnUiThread(new Runnable() {
			@Override
			public void run() {
				startVideoActivity();
			}
		});
	}
}

```

VideoActivity.java

```

package io.slib.examplejni;

import android.os.Bundle;
import android.util.Log;

import slib.platform.android.SlibActivity;

/**
 * Created by bils on 26/02/2018.
 */

public class VideoActivity extends SlibActivity {

    static {
        System.loadLibrary("native-lib");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        Log.d("VideoActivity", "onCreate");

    }
}
```

I saw that you were drawing on a window object so I added those to the manifest:

```
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature android:glEsVersion="0x00020000" android:required="true" />

    <uses-permission android:name="android.permission.CAMERA" />
```

Let me know if I'm missing something and thanks a lot for your help

**Comment by fred1218zh** [comment]
`Camera` can listen incoming video frames via listener interface.
If you want to display that video frames, you have to add a GLSurfaceView, and draw the grabbed frames by OpenGL in `cpp`

**Comment by bilsou** [comment]
Indeed I saw straight after posting my message that you had a `setOnCaptureVideoFrame` on the `VideoCapture` base type. I am not sure what you mean, can I draw directly the `VideoCaptureFrame` frames on the Java side or do I need to use the C++ `RenderEngine` present in the library ?
Would you have any small example/sample app that would show the camera feed ? IMHO it would be much easier to directly look at that than going back and forth via Github.

**Comment by fred1218zh** [comment]
You have to render that in c++. I think you can refer `src/ui/camera_view.cpp`
The example will be cross-platform camera rendering example.
I can provide the example late this week because I am working hard on other side.

**Comment by bilsou** [comment]
Ok I will look into `camera_view.cpp`. 
I reckon it's a mere normal view I can add to my layout ? 
My final goal is to actually retrieve the video frames directly as textures and  pass that 
C++ <-> Java/ObjC. I don't really want to manipulate buffers as it is slower than directly rendering textures. So on Android I would like to directly build a `SurfaceTexure` object and on iOS `EAGLView`.
I will be waiting for the example then, once again thanks a lot for your help.

**Comment by bilsou** [comment]
Sorry for bothering you once again, I know I said I would wait for your example app. But as there is no documentation, I'm just doing some manual tests with regards to some Slib functionalities.
I'm trying to save the`VideoCaptureFrame` to disk via its `BitmapData`. 
Here is what I currently have which does not work.

```
extern "C"
JNIEXPORT void JNICALL
Java_io_slib_examplejni_MainActivity_startCameraCpp(JNIEnv *env, jobject self) {
	JniGlobal<jobject> activity(self);

	const auto camApp = CameraApp::getApp();
	camApp->setCamera(Camera::create(CameraParam()));

	const auto camera = camApp->getCamera();
	camera->start();
    camera->setOnCaptureVideoFrame([](VideoCapture* capture, VideoCaptureFrame* frame) {
        Log("JNI", "%d %d", frame->image.width, frame->image.height);
		auto image = Image::create(frame->image);
		auto file = File::openForWrite(std::string("VideoFrameImage.jpg"));
		auto filePath = file->getPath();
		image->saveToJPEG(filePath);
    });

	MainActivity::startCameraJava.call(activity.get());

	Log("JNI", "Started camera");
}
```

I added the permissions to the manifest


```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

Is there any way of saving the image to the app documents' folder ?

**Comment by fred1218zh** [comment]
You should not call `File::openForWrite`, since it is opening file and lock the writing operation.
Please refer following snippet
```
Log("JNI", "%d %d", frame->image.width, frame->image.height);
auto image = Image::create(frame->image);
image->saveToJPEG("/mnt/sdcard/test.jpg");
```

**Comment by bilsou** [comment]
Thanks a lot, it works.
I am really going to wait this week for your sample app to have a better understanding on how the things I am interested in work out.
Your library looks amazingly done and does a lot of useful things and as it is open source I have no right to complain whatsoever. But, to be honest, the lack of examples and documentation is just a huge blocker. I am wasting so much time just going into the sources and looking how things are working together. So I have no right to ask for more, but if I see I keep on spending huge amount of time searching through the files for the most basic features, I will just give up on it. 
Looking forward to getting your sample app though, thanks again.
